// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://adgqfblvdavfikofqegh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFkZ3FmYmx2ZGF2Zmlrb2ZxZWdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg5NTA1MjksImV4cCI6MjA1NDUyNjUyOX0.mzMXSKFgC3jXBbBFAEXLXCwLL41-f4pAUC0bgIPqyMc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);